name: test
on: [push, pull_request]

jobs:
  test:
    env:
      RUST_BACKTRACE: "1"
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        channel: [stable]
        os: [ubuntu]
    steps:
    - uses: actions/checkout@v2
    - run: rustup default ${{ matrix.channel }}
    - run: cargo build --verbose --all-targets
    # not running integration tests
    - run: cargo test --lib ucare -- --nocapture
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo clippy
